import os
from dotenv import load_dotenv

from contracts.v1.ruleset import load_ruleset_version

load_dotenv()

ENV_MODE = os.getenv("YINGMU_ENV", "mock").lower()
if ENV_MODE not in {"mock", "live"}:
    raise RuntimeError("YINGMU_ENV must be mock or live")

EZVIZ_BASE_URL = "http://127.0.0.1:8001/mock" if ENV_MODE == "mock" else "https://open.ys7.com/api/lapp"
EZVIZ_APP_KEY = os.getenv("EZVIZ_APP_KEY", "mock_default_key" if ENV_MODE == "mock" else "")
EZVIZ_APP_SECRET = os.getenv("EZVIZ_APP_SECRET", "mock_default_secret" if ENV_MODE == "mock" else "")
EZVIZ_ACCESS_TOKEN = os.getenv("EZVIZ_ACCESS_TOKEN", "")
EZVIZ_ACCESS_TOKEN_EXPIRES_AT = os.getenv("EZVIZ_ACCESS_TOKEN_EXPIRES_AT", "")
EZVIZ_DEVICE_SERIAL = os.getenv("EZVIZ_DEVICE_SERIAL", "")
EZVIZ_CHANNEL_NO = int(os.getenv("EZVIZ_CHANNEL_NO", "1"))
EZVIZ_LIVE_PROTOCOL = int(os.getenv("EZVIZ_LIVE_PROTOCOL", "4"))
EZVIZ_LIVE_QUALITY = int(os.getenv("EZVIZ_LIVE_QUALITY", "1"))
EZVIZ_CAPTURE_TIMEOUT_SECONDS = float(os.getenv("EZVIZ_CAPTURE_TIMEOUT_SECONDS", "45"))
EZVIZ_STATUS_TIMEOUT_SECONDS = float(os.getenv("EZVIZ_STATUS_TIMEOUT_SECONDS", "5"))
YINGMU_CAPTURE_MEDIA_MODE = os.getenv("YINGMU_CAPTURE_MEDIA_MODE", "SNAPSHOT").upper()
YINGMU_VIDEO_CAPTURE_SECONDS = int(os.getenv("YINGMU_VIDEO_CAPTURE_SECONDS", "8"))
YINGMU_FFMPEG_BINARY = os.getenv("YINGMU_FFMPEG_BINARY", "ffmpeg")
YINGMU_STREAM_BUFFER_ENABLED = (
    os.getenv("YINGMU_STREAM_BUFFER_ENABLED", "false").lower() == "true"
)
YINGMU_STREAM_BUFFER_ROOT = os.getenv("YINGMU_STREAM_BUFFER_ROOT", "")
YINGMU_STREAM_BUFFER_SEGMENT_SECONDS = int(
    os.getenv("YINGMU_STREAM_BUFFER_SEGMENT_SECONDS", "2")
)
YINGMU_STREAM_BUFFER_PRE_SECONDS = int(
    os.getenv("YINGMU_STREAM_BUFFER_PRE_SECONDS", "10")
)
YINGMU_STREAM_BUFFER_POST_SECONDS = int(
    os.getenv("YINGMU_STREAM_BUFFER_POST_SECONDS", "20")
)
YINGMU_STREAM_BUFFER_RETENTION_SECONDS = int(
    os.getenv("YINGMU_STREAM_BUFFER_RETENTION_SECONDS", "60")
)
YINGMU_STREAM_BUFFER_RECONNECT_SECONDS = float(
    os.getenv("YINGMU_STREAM_BUFFER_RECONNECT_SECONDS", "3")
)
YINGMU_STREAM_BUFFER_SELECTION_RETRY_SECONDS = float(
    os.getenv("YINGMU_STREAM_BUFFER_SELECTION_RETRY_SECONDS", "8")
)
YINGMU_STREAM_BUFFER_MAX_ALARM_DELAY_SECONDS = int(
    os.getenv("YINGMU_STREAM_BUFFER_MAX_ALARM_DELAY_SECONDS", "20")
)
YINGMU_STREAM_BUFFER_STALL_SECONDS = int(
    os.getenv("YINGMU_STREAM_BUFFER_STALL_SECONDS", "8")
)
EZVIZ_DEVICE_VERIFY_CODE = os.getenv("EZVIZ_DEVICE_VERIFY_CODE", "")
EZVIZ_LIVE_PLAYBACK_VERIFIED = (
    os.getenv("EZVIZ_LIVE_PLAYBACK_VERIFIED", "false").lower() == "true"
)
EZVIZ_VOICE_VERIFIED = os.getenv("EZVIZ_VOICE_VERIFIED", "false").lower() == "true"
EZVIZ_RESIDENT_ID = os.getenv("EZVIZ_RESIDENT_ID", "")
EZVIZ_DEVICE_MODEL = os.getenv("EZVIZ_DEVICE_MODEL", "EZVIZ_C6C")
YINGMU_PRIVATE_MEDIA_ROOT = os.getenv("YINGMU_PRIVATE_MEDIA_ROOT", "")
YINGMU_MEDIA_ACCESS_TOKEN = os.getenv("YINGMU_MEDIA_ACCESS_TOKEN", "")
YINGMU_MEDIA_AUTO_SESSION = os.getenv("YINGMU_MEDIA_AUTO_SESSION", "false").lower() == "true"
YINGMU_BFF_SESSION_SECRET = os.getenv("YINGMU_BFF_SESSION_SECRET", "")
YINGMU_BFF_USERNAME = os.getenv("YINGMU_BFF_USERNAME", "")
YINGMU_BFF_PASSWORD_SHA256 = os.getenv("YINGMU_BFF_PASSWORD_SHA256", "").lower()
YINGMU_BFF_SESSION_TTL_SECONDS = int(os.getenv("YINGMU_BFF_SESSION_TTL_SECONDS", "900"))
YINGMU_BFF_COOKIE_SECURE = os.getenv(
    "YINGMU_BFF_COOKIE_SECURE", "true" if ENV_MODE == "live" else "false"
).lower() == "true"
YINGMU_LIVE_VIEW_ENABLED = os.getenv("YINGMU_LIVE_VIEW_ENABLED", "false").lower() == "true"
YINGMU_LIVE_STREAM_TIMEOUT_SECONDS = float(
    os.getenv("YINGMU_LIVE_STREAM_TIMEOUT_SECONDS", "30")
)
YINGMU_CAMERA_POSITION_ID = os.getenv("YINGMU_CAMERA_POSITION_ID", "")
YINGMU_AUTHORIZATION_RECORD_ID = os.getenv("YINGMU_AUTHORIZATION_RECORD_ID", "")
YINGMU_RETENTION_UNTIL = os.getenv("YINGMU_RETENTION_UNTIL", "")
YINGMU_SNAPSHOT_MAX_BYTES = int(os.getenv("YINGMU_SNAPSHOT_MAX_BYTES", str(10 * 1024 * 1024)))
YINGMU_SNAPSHOT_DOWNLOAD_TIMEOUT_SECONDS = float(
    os.getenv("YINGMU_SNAPSHOT_DOWNLOAD_TIMEOUT_SECONDS", "30")
)
AGENT_LLM_BASE_URL = os.getenv("AGENT_LLM_BASE_URL", "")
AGENT_LLM_API_KEY = os.getenv("AGENT_LLM_API_KEY", "") or os.getenv("EZVIZ_API_KEY", "")
AGENT_LLM_MODEL = os.getenv("AGENT_LLM_MODEL", "")
AGENT_LLM_TIMEOUT_SECONDS = float(os.getenv("AGENT_LLM_TIMEOUT_SECONDS", "30"))
AGENT_LLM_MAX_OUTPUT_TOKENS = int(os.getenv("AGENT_LLM_MAX_OUTPUT_TOKENS", "400"))
YINGMU_SCENE_CONFIG_ID = os.getenv("YINGMU_SCENE_CONFIG_ID", "scene-living-room-v1")
YINGMU_SCENE_CONFIG_DIR = os.getenv("YINGMU_SCENE_CONFIG_DIR", "scene-calibrations")
YINGMU_LOCATION = os.getenv("YINGMU_LOCATION", "living_room")
YINGMU_ALGORITHM_TIMEOUT_SECONDS = float(
    os.getenv("YINGMU_ALGORITHM_TIMEOUT_SECONDS", "90")
)
EZVIZ_WEBHOOK_SECRET = os.getenv("EZVIZ_WEBHOOK_SECRET", "")
EZVIZ_WEBHOOK_MAX_AGE_SECONDS = int(os.getenv("EZVIZ_WEBHOOK_MAX_AGE_SECONDS", "300"))
EZVIZ_WEBHOOK_ALLOW_UNSIGNED_TEST = (
    os.getenv("EZVIZ_WEBHOOK_ALLOW_UNSIGNED_TEST", "false").lower() == "true"
)
CONTROL_TOKEN = os.getenv("YINGMU_CONTROL_TOKEN", "")
CORS_ORIGINS = tuple(
    origin.strip()
    for origin in os.getenv(
        "YINGMU_CORS_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if origin.strip()
)

TOKEN_REFRESH_OFFSET = 60
_RULESET = load_ruleset_version(os.getenv("YINGMU_RULESET_VERSION", "ruleset-v1.2"))
RULESET_VERSION = _RULESET.version
FOREWARNING_RULESET_VERSION = os.getenv(
    "YINGMU_FOREWARNING_RULESET_VERSION",
    RULESET_VERSION if RULESET_VERSION in {"ruleset-v1.4", "ruleset-v1.5"} else "ruleset-v1.3-min",
)
SCHEMA_VERSION = "1.0"
# Risk thresholds have one source of truth: the active versioned ruleset. Environment
# overrides previously let FastAPI and the agent assign different meanings.
MIN_EVIDENCE_QUALITY = _RULESET.thresholds["data_quality"]
MIN_EVIDENCE_CONFIDENCE = _RULESET.thresholds["confidence"]

if ENV_MODE == "live" and (not EZVIZ_APP_KEY or not EZVIZ_APP_SECRET or not EZVIZ_DEVICE_SERIAL):
    raise RuntimeError("live mode requires EZVIZ_APP_KEY, EZVIZ_APP_SECRET and EZVIZ_DEVICE_SERIAL")

if EZVIZ_CAPTURE_TIMEOUT_SECONDS <= 0:
    raise RuntimeError("EZVIZ_CAPTURE_TIMEOUT_SECONDS must be positive")
if EZVIZ_STATUS_TIMEOUT_SECONDS <= 0:
    raise RuntimeError("EZVIZ_STATUS_TIMEOUT_SECONDS must be positive")
if EZVIZ_LIVE_PROTOCOL not in {2, 4}:
    raise RuntimeError("EZVIZ_LIVE_PROTOCOL must be 2 (HLS) or 4 (FLV)")
if EZVIZ_LIVE_QUALITY not in {1, 2}:
    raise RuntimeError("EZVIZ_LIVE_QUALITY must be 1 (main stream) or 2 (sub stream)")
if YINGMU_LIVE_STREAM_TIMEOUT_SECONDS <= 0:
    raise RuntimeError("YINGMU_LIVE_STREAM_TIMEOUT_SECONDS must be positive")
if YINGMU_CAPTURE_MEDIA_MODE not in {"SNAPSHOT", "VIDEO"}:
    raise RuntimeError("YINGMU_CAPTURE_MEDIA_MODE must be SNAPSHOT or VIDEO")
if not 1 <= YINGMU_VIDEO_CAPTURE_SECONDS <= 60:
    raise RuntimeError("YINGMU_VIDEO_CAPTURE_SECONDS must be between 1 and 60")
if not 1 <= YINGMU_STREAM_BUFFER_SEGMENT_SECONDS <= 10:
    raise RuntimeError("YINGMU_STREAM_BUFFER_SEGMENT_SECONDS must be between 1 and 10")
if not 0 <= YINGMU_STREAM_BUFFER_PRE_SECONDS <= 60:
    raise RuntimeError("YINGMU_STREAM_BUFFER_PRE_SECONDS must be between 0 and 60")
if not 1 <= YINGMU_STREAM_BUFFER_POST_SECONDS <= 60:
    raise RuntimeError("YINGMU_STREAM_BUFFER_POST_SECONDS must be between 1 and 60")
if YINGMU_STREAM_BUFFER_RETENTION_SECONDS < (
    YINGMU_STREAM_BUFFER_PRE_SECONDS
    + YINGMU_STREAM_BUFFER_POST_SECONDS
    + 2 * YINGMU_STREAM_BUFFER_SEGMENT_SECONDS
):
    raise RuntimeError("YINGMU_STREAM_BUFFER_RETENTION_SECONDS is too short for the capture window")
if YINGMU_STREAM_BUFFER_RETENTION_SECONDS > 300:
    raise RuntimeError("YINGMU_STREAM_BUFFER_RETENTION_SECONDS must not exceed 300")
if YINGMU_STREAM_BUFFER_RECONNECT_SECONDS <= 0:
    raise RuntimeError("YINGMU_STREAM_BUFFER_RECONNECT_SECONDS must be positive")
if not 0 <= YINGMU_STREAM_BUFFER_SELECTION_RETRY_SECONDS <= 30:
    raise RuntimeError("YINGMU_STREAM_BUFFER_SELECTION_RETRY_SECONDS must be between 0 and 30")
if not 0 <= YINGMU_STREAM_BUFFER_MAX_ALARM_DELAY_SECONDS <= 120:
    raise RuntimeError("YINGMU_STREAM_BUFFER_MAX_ALARM_DELAY_SECONDS must be between 0 and 120")
if YINGMU_STREAM_BUFFER_RETENTION_SECONDS < (
    YINGMU_STREAM_BUFFER_MAX_ALARM_DELAY_SECONDS
    + YINGMU_STREAM_BUFFER_PRE_SECONDS
    + YINGMU_STREAM_BUFFER_POST_SECONDS
    + 2 * YINGMU_STREAM_BUFFER_SEGMENT_SECONDS
):
    raise RuntimeError("YINGMU_STREAM_BUFFER_RETENTION_SECONDS is too short for delayed alarms")
if not 2 * YINGMU_STREAM_BUFFER_SEGMENT_SECONDS <= YINGMU_STREAM_BUFFER_STALL_SECONDS <= 60:
    raise RuntimeError("YINGMU_STREAM_BUFFER_STALL_SECONDS must be between two segments and 60")
if YINGMU_SNAPSHOT_MAX_BYTES <= 0:
    raise RuntimeError("YINGMU_SNAPSHOT_MAX_BYTES must be positive")
if YINGMU_SNAPSHOT_DOWNLOAD_TIMEOUT_SECONDS <= 0:
    raise RuntimeError("YINGMU_SNAPSHOT_DOWNLOAD_TIMEOUT_SECONDS must be positive")
if AGENT_LLM_TIMEOUT_SECONDS <= 0:
    raise RuntimeError("AGENT_LLM_TIMEOUT_SECONDS must be positive")
if AGENT_LLM_MAX_OUTPUT_TOKENS <= 0:
    raise RuntimeError("AGENT_LLM_MAX_OUTPUT_TOKENS must be positive")
if not 0.1 <= YINGMU_ALGORITHM_TIMEOUT_SECONDS <= 120:
    raise RuntimeError("YINGMU_ALGORITHM_TIMEOUT_SECONDS must be between 0.1 and 120")
