from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.config import RULESET_VERSION
from backend.db.models import Asset, Evidence, Observation
from backend.schemas.evidence import EvidenceCreate
from backend.service.errors import ServiceError
from backend.service.risk_service import evaluate, ruleset
from backend.service.rule_log_service import log_rule
from backend.service.serialization import dumps, evidence_dict
from backend.service.serialization import aware
from contracts.v1.semantics import EvidenceSemanticError, validate_evidence_semantics
from contracts.v1.evidence_types import INTERNAL_EVIDENCE_TYPES


def _log_evaluation(payload: EvidenceCreate, request_id: str, result: dict) -> None:
    # The persisted RuleTrace is the canonical log payload. Request metadata is
    # deliberately kept outside it so API, database and page semantics cannot drift.
    log_rule(result["trace"])


async def _create_quality_evidence(
    db: AsyncSession,
    payload: EvidenceCreate,
) -> str | None:
    if (
        ruleset.usable(payload.confidence, payload.data_quality)
    ):
        return None

    evidence_id = f"sys-quality-{payload.evidence_id}"
    existing = (await db.execute(
        select(Evidence).where(Evidence.evidence_id == evidence_id)
    )).scalar_one_or_none()
    if existing:
        return evidence_id

    db.add(Evidence(
        schema_version="1.0",
        evidence_id=evidence_id,
        observation_ids=dumps(payload.observation_ids),
        resident_id=payload.resident_id,
        timestamp=payload.timestamp,
        risk_domain="SYSTEM",
        evidence_type="quality_gate_failed",
        severity=0.0,
        confidence=1.0,
        data_quality=payload.data_quality,
        baseline_value=None,
        current_value=payload.data_quality,
        baseline_deviation=None,
        time_scale=payload.time_scale,
        location=payload.location,
        explanation="数据质量或置信度低于工程门槛，本条证据不参与风险升级",
        adapter_version=RULESET_VERSION,
        source_mode=payload.source_mode.value,
        simulated=payload.simulated,
    ))
    await db.commit()
    return evidence_id


async def create_evidence(
    db: AsyncSession,
    payload: EvidenceCreate,
    request_id: str,
):
    if payload.evidence_type in INTERNAL_EVIDENCE_TYPES:
        raise ServiceError(
            422,
            "INTERNAL_EVIDENCE_FORBIDDEN",
            "internal Evidence types can only be generated by backend aggregation",
        )
    existing = (await db.execute(
        select(Evidence).where(Evidence.evidence_id == payload.evidence_id)
    )).scalar_one_or_none()
    if existing:
        existing_payload = evidence_dict(existing)
        existing_payload["timestamp"] = existing_payload["timestamp"].isoformat()
        if dumps(existing_payload) != dumps(payload.model_dump(mode="json")):
            raise ServiceError(
                409,
                "EVIDENCE_ID_CONFLICT",
                "evidence_id exists with different content",
            )
        result = await evaluate(
            db,
            payload.resident_id,
            payload.timestamp,
            payload.evidence_id,
            duplicate=True,
        )
        _log_evaluation(payload, request_id, result)
        return evidence_dict(existing), False, True, result

    observations = (await db.execute(
        select(Observation).where(
            Observation.observation_id.in_(payload.observation_ids)
        )
    )).scalars().all()
    found = {row.observation_id for row in observations}
    missing = [item for item in payload.observation_ids if item not in found]
    if missing:
        raise ServiceError(
            409,
            "OBSERVATION_NOT_FOUND",
            f"observations do not exist: {missing}",
        )
    if any(row.resident_id != payload.resident_id for row in observations):
        raise ServiceError(
            409,
            "RESIDENT_MISMATCH",
            "Evidence and Observation resident_id must match",
        )
    if any(
        row.source_mode != payload.source_mode.value
        or row.simulated != payload.simulated
        for row in observations
    ):
        raise ServiceError(
            409,
            "SOURCE_MISMATCH",
            "Evidence must inherit source_mode and simulated",
        )

    if payload.risk_domain.value == "FALL" and payload.source_mode.value == "RECORDED_REPLAY":
        authorization_check_at = max(aware(payload.timestamp), datetime.now(timezone.utc))
        asset_ids = {row.asset_id for row in observations if row.asset_id}
        if any(not row.asset_id for row in observations):
            raise ServiceError(409, "ASSET_REQUIRED", "recorded fall Observations must reference an authorized asset")
        assets = (await db.execute(select(Asset).where(Asset.asset_id.in_(asset_ids)))).scalars().all()
        asset_by_id = {item.asset_id: item for item in assets}
        missing_assets = sorted(asset_ids - set(asset_by_id))
        if missing_assets:
            raise ServiceError(409, "ASSET_NOT_FOUND", f"authorized assets do not exist: {missing_assets}")
        for observation in observations:
            asset = asset_by_id[observation.asset_id]
            if asset.source_mode != observation.source_mode or asset.simulated != observation.simulated:
                raise ServiceError(409, "ASSET_SOURCE_MISMATCH", "Asset and Observation source_mode/simulated must match")
            if asset.device_model != "EZVIZ_C6C":
                raise ServiceError(409, "ASSET_DEVICE_MISMATCH", "recorded fall Evidence requires an EZVIZ_C6C asset")
            if asset.authorization_status != "AUTHORIZED" or not asset.authorization_record_id:
                raise ServiceError(409, "ASSET_NOT_AUTHORIZED", "recorded C6c asset is not authorized")
            if not asset.retention_until:
                raise ServiceError(409, "ASSET_RETENTION_REQUIRED", "recorded C6c asset must declare a retention deadline")
            if aware(asset.retention_until) < authorization_check_at:
                raise ServiceError(409, "ASSET_AUTHORIZATION_EXPIRED", "recorded C6c asset authorization has expired")

    try:
        validate_evidence_semantics(payload, observations)
    except EvidenceSemanticError as error:
        raise ServiceError(422, "EVIDENCE_SEMANTICS_INVALID", str(error)) from error

    data = payload.model_dump(exclude={"observation_ids"})
    row = Evidence(**data, observation_ids=dumps(payload.observation_ids))
    db.add(row)
    await db.commit()
    await db.refresh(row)

    system_evidence_id = await _create_quality_evidence(db, payload)
    result = await evaluate(
        db,
        payload.resident_id,
        payload.timestamp,
        payload.evidence_id,
        system_evidence_id=system_evidence_id,
    )
    _log_evaluation(payload, request_id, result)
    return evidence_dict(row), True, False, result
